title : 'seoMyungInGitTechBlog'
name: 'seoMyungInGitTechBlog'
description: '테크 & 개발 블로그'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

collections:
  news:
    title: Notice
    default_open: false
    output: true
  posts:
    title: TIL (Today I learned)
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Essays
      permalink: /post/:title
  - scope:
      type: news
    values:
      title: News
      permalink: /news/:title

plugins:
  - jekyll-sitemap
